name: XiaoSign
main: zbv5.cn.XiaoSign.Main
version: 1.2.0
api: 1.0.0
author: 逍遥
softdepend:
  - PlaceholderAPI
permissions:
  XiaoSign.commands:
    description: 默认权限
    default: true
  XiaoSign.commands.open:
    description: 打开签到页面所需权限
    default: true
  XiaoSign.Reward.default:
    description: 签到默认组所需权限
    default: true
  XiaoSign.commands.give:
    description: 给予补签卡所需权限
    default: op
  XiaoSign.commands.reload:
    description: 重载配置所需权限
    default: op