name: XiaoSign
main: zbv5.cn.XiaoSign.Main
version: 1.1.1
api: 1.0.0
author: 逍遥
softdepend:
  - PlaceholderAPI
commands:
  XiaoSign:
    description: 签到
    aliases: ["xsign", "sign"]
permissions:
  XiaoSign.commands.open:
    description: 打开签到页面所需权限
    default: true
  XiaoSign.Reward.default:
    description: 签到默认组所需权限
    default: true
  XiaoSign.commands.give:
    description: 给予补签卡所需权限
    default: op
  XiaoSign.commands.reload:
    description: 重载配置所需权限
    default: op